#!/bin/bash
set -e

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid

echo "Configuring Apache2 environment variables..."

# Set ServerName of created container
export APACHE_SERVERNAME="${APACHE_SERVERNAME:-$(cat /etc/hostname)}"

# Support for configuration overrides
include_conf ()
{
	file=$1

	if [[ -f "$file" ]]; then
		echo "Including configuration overrides from $file"
		cp "$file" /usr/local/apache2/conf/custom
	fi
}
include_conf "/var/www/.docksal/etc/apache/httpd-vhost-overrides.conf"
include_conf "/var/www/.docksal/etc/apache/httpd-vhosts.conf"

# Run in foreground
args="-DFOREGROUND"

# Basic HTTP Authentication
if [[ "$APACHE_BASIC_AUTH_USER" != "" ]] && [[ "$APACHE_BASIC_AUTH_PASS" != "" ]]; then
	echo "Enabling Basic HTTP Authentication [$APACHE_BASIC_AUTH_USER:$APACHE_BASIC_AUTH_PASS]"
	htpasswd -cb /usr/local/apache2/htpasswd "$APACHE_BASIC_AUTH_USER" "$APACHE_BASIC_AUTH_PASS"
	args+=" -DBasicAuth"
fi

# Secondary Basic HTTP Authentication
if [[ "$APACHE_BASIC_AUTH_USER_SECONDARY" != "" ]] && [[ "$APACHE_BASIC_AUTH_PASS_SECONDARY" != "" ]]; then
  echo "Enabling Basic HTTP Authentication [$APACHE_BASIC_AUTH_USER_SECONDARY:$APACHE_BASIC_AUTH_PASS_SECONDARY]"
  if [ -f /usr/local/apache2/htpasswd ]
  then
    htpasswd -b /usr/local/apache2/htpasswd "$APACHE_BASIC_AUTH_USER_SECONDARY" "$APACHE_BASIC_AUTH_PASS_SECONDARY"
  else
    htpasswd -cb /usr/local/apache2/htpasswd "$APACHE_BASIC_AUTH_USER_SECONDARY" "$APACHE_BASIC_AUTH_PASS_SECONDARY"
  fi
	args+=" -DBasicAuth"
fi


cat /usr/local/apache2/htpasswd

exec httpd ${args}
